os: linux
language: c
dist: trusty
group: stable
compiler: gcc
env:
  - O=generic B=centos7 P=hyperv V=1.8.50 H=a065ccf1d9088915d23c6fe2867c2faea28685f01a81498db6fb28e23018a570
  - O=generic B=centos7 P=libvirt V=1.8.50 H=7b71f154202b6d69878539412eee75e04a4903e697aef3c6fefe4a18ae57aa0e
  - O=generic B=centos7 P=parallels V=1.8.50 H=500f29c5990526b14b3335d1196384874ae80818b136896d797740d27237e049
  - O=generic B=centos7 P=virtualbox V=1.8.50 H=f5fcf13a8091d746f223129e846c957ea0efeb2b61fc39c0d394e28a4c13b43e
notifications:
  email:
    recipients:
      - make@roboxes.org
    on_success: change
    on_failure: always
script:
  - touch failure.log
  - (for ((i = 0; i < 60; ++i)); do date ; sleep 480; done) & LOOP_PID=$! ; disown
  -  HASH=`curl --silent --location --retry 10 --retry-delay 120 --max-redirs 10 --user-agent "${AGENT}" https://vagrantcloud.com/$O/boxes/$B/versions/$V/providers/$P.box | sha256sum | tr -d '  -'`
  - if [ "$HASH" != "$H" ]; then echo $O $B $P $V failed | tee failure.log ; fi
  - export RESULT=`cat failure.log | wc -l`
  - if [[ $RESULT != 0 ]]; then exit 1; fi
